### ISSUE TITLE
Use relative paths when linking

### ISSUE THREAD

**Issue by jim-rosales** [AA041310/prj-rev-bwfs-dasmoto#1]
When I downloaded your project initially this is how it is rendered:
<img width="1667" alt="screen shot 2018-01-26 at 11 34 29 am" src="https://user-images.githubusercontent.com/28379087/35457179-e7211730-028c-11e8-8894-d971b6ee2425.png">

The reason for this is because you used an [absolute file](https://en.wikipedia.org/wiki/Path_%28computing%29#Absolute_and_relative_paths) path when linking the CSS file. 

When linking files or images, it is best practice to use relative file paths considering this will allow you to move the project to a different computer and everything will still work. 

The path meanings:

`/` is the root of the current drive;
`./` is the current directory; Note usually you'd access the current directory or the parent 
`../` is the parent of the current directory.

In this case, it would mean you'd change the path to link your file to:
`<link href="./Resources/style.css" type="text/css" rel="stylesheet"/>`

https://github.com/AA041310/prj-rev-bwfs-dasmoto/blob/c044b145d21f24fe60e1a2cb7a40e505bde3cc6e/Dasmoto's%20Arts%20%26%20Crafts/index.html#L6

**Comment by AA041310** [comment]
changed
