### ISSUE TITLE
Remove extra ending Div tag

### ISSUE THREAD

**Issue by jim-rosales** [AA041310/prj-rev-bwfs-dasmoto#2]
This ending div tag does not have a start so you can remove it. 

https://github.com/AA041310/prj-rev-bwfs-dasmoto/blob/c044b145d21f24fe60e1a2cb7a40e505bde3cc6e/Dasmoto's%20Arts%20%26%20Crafts/index.html#L10

**Comment by AA041310** [comment]
changed
