### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by jim-rosales** [AA041310/prj-rev-bwfs-dasmoto#3]
When you declared the start of the div, you added a `/` after naming your class. This isn't needed an might cause bugs later on. 
`<div class="paint"/>`

You should have:
<div class="paint">

https://github.com/AA041310/prj-rev-bwfs-dasmoto/blob/c044b145d21f24fe60e1a2cb7a40e505bde3cc6e/Dasmoto's%20Arts%20%26%20Crafts/index.html#L23

**Comment by AA041310** [comment]
changed
