### ISSUE TITLE
Use character entity

### ISSUE THREAD

**Issue by jim-rosales** [AA041310/prj-rev-bwfs-dasmoto#4]
It is considered to be best practice to use a [characters entity reference](https://developer.mozilla.org/en-US/docs/Glossary/Entity) when linking certain characters like the ampersand symbol.

In this case, you'd replace the `&` with `&amp;`

https://github.com/AA041310/prj-rev-bwfs-dasmoto/blob/c044b145d21f24fe60e1a2cb7a40e505bde3cc6e/Dasmoto's%20Arts%20%26%20Crafts/index.html#L9

**Comment by AA041310** [comment]
changed
