### ISSUE TITLE
Add the alt attribute

### ISSUE THREAD

**Issue by jim-rosales** [AA041310/prj-rev-bwfs-dasmoto#6]
Usually, when an image is included on a site, we add the [alt attribute](https://en.wikipedia.org/wiki/Alt_attribute) considering it is used for both [accessibility](https://www.codecademy.com/articles/accessibility) and as a backup, in case your image can't be rendered. 

https://github.com/AA041310/prj-rev-bwfs-dasmoto/blob/c044b145d21f24fe60e1a2cb7a40e505bde3cc6e/Dasmoto's%20Arts%20%26%20Crafts/index.html#L19

**Comment by AA041310** [comment]
added
