### ISSUE TITLE
Reduce duplicate CSS

### ISSUE THREAD

**Issue by jim-rosales** [AA041310/prj-rev-bwfs-dasmoto#7]
You have these lines of code for two other sections. Usually, when we see that multiple elements are using the same styles, it is best practice to find a way to prevent writing it twice.

In this case, you can just do the following:

div h2 {
    color: white;
    font-size: 32px;
}

Then all your H2s with have the correct color and font-size. 

https://github.com/AA041310/prj-rev-bwfs-dasmoto/blob/c044b145d21f24fe60e1a2cb7a40e505bde3cc6e/Dasmoto's%20Arts%20%26%20Crafts/Resources/style.css#L23-L26

**Comment by AA041310** [comment]
changed
