### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by jim-rosales** [AA041310/prj-rev-bwfs-dasmoto#8]
Grade: Needs improvement

Summary:
Congrats on finishing the Dasmoto project! You did an excellent job using various classes and ids to group or separate multiple elements. Apart from this, your class and id names were descriptive which made it easy to understand what their use was. 

I suggest you pay particular attention to the following issues: #1, #2, #3, #6 as those all dealt with syntax issues. As your projects become more complex having correct syntax will lessen the number of bugs your encounter thus reducing the amount of time you spend completing your project overall. 

As extra practice and as an extra review consider going over this [HTML](https://gist.github.com/jim-rosales/c1446e66054c97071406610be771fa79) and [CSS](https://gist.github.com/jim-rosales/2f5cfda50385ffddc1225f0e8a9f4807) solution for the project. This will allow you to see an alternate way of accomplishing the same end goal.

**Comment by AA041310** [comment]
Thank you for your detailed explantion. I change my code and add my code version 2 to GitHub.
Yolanda
